/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_omusic_decorder_Mpg123Decoder */

#ifndef _Included_cc_omusic_decorder_Mpg123Decoder
#define _Included_cc_omusic_decorder_Mpg123Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_omusic_decorder_Mpg123Decoder
 * Method:    openFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_cc_omusic_decorder_Mpg123Decoder_openFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cc_omusic_decorder_Mpg123Decoder
 * Method:    readSamples
 * Signature: (J[SII)I
 */
JNIEXPORT jint JNICALL Java_cc_omusic_decorder_Mpg123Decoder_readSamples
  (JNIEnv *, jobject, jlong, jshortArray, jint, jint);

/*
 * Class:     cc_omusic_decorder_Mpg123Decoder
 * Method:    skipSamples
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_cc_omusic_decorder_Mpg123Decoder_skipSamples
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cc_omusic_decorder_Mpg123Decoder
 * Method:    getNumChannels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cc_omusic_decorder_Mpg123Decoder_getNumChannels
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_omusic_decorder_Mpg123Decoder
 * Method:    getRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cc_omusic_decorder_Mpg123Decoder_getRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_omusic_decorder_Mpg123Decoder
 * Method:    getLength
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_cc_omusic_decorder_Mpg123Decoder_getLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cc_omusic_decorder_Mpg123Decoder
 * Method:    closeFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cc_omusic_decorder_Mpg123Decoder_closeFile
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
