/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_omusic_decorder_WavDecoder */

#ifndef _Included_cc_omusic_decorder_WavDecoder
#define _Included_cc_omusic_decorder_WavDecoder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
