/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_omusic_decorder_WavDecoder_WavInputStream */

#ifndef _Included_cc_omusic_decorder_WavDecoder_WavInputStream
#define _Included_cc_omusic_decorder_WavDecoder_WavInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef cc_omusic_decorder_WavDecoder_WavInputStream_MAX_SKIP_BUFFER_SIZE
#define cc_omusic_decorder_WavDecoder_WavInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
