/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_omusic_FingerprintDecodeJin_FingerprintWraper */

#ifndef _Included_cc_omusic_FingerprintDecodeJin_FingerprintWraper
#define _Included_cc_omusic_FingerprintDecodeJin_FingerprintWraper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_omusic_FingerprintDecodeJin_FingerprintWraper
 * Method:    getFingerprint
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_cc_omusic_FingerprintDecodeJin_FingerprintWraper_getFingerprint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
